"""empty message

Revision ID: 9a60214f120f
Revises: 
Create Date: 2024-11-25 12:08:46.156516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a60214f120f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station',
    sa.Column('station_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('station_id')
    )
    op.create_table('cctv',
    sa.Column('cctv_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('cctv_idx', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['station.station_id'], ),
    sa.PrimaryKeyConstraint('cctv_id')
    )
    op.create_table('robot',
    sa.Column('robot_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['station.station_id'], ),
    sa.PrimaryKeyConstraint('robot_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('passowrd', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['station.station_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('cctv_log',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cctv_id', sa.Integer(), nullable=False),
    sa.Column('video_address', sa.String(length=500), nullable=True),
    sa.Column('registerd', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cctv_id'], ['cctv.cctv_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('robot_log',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('robot_id', sa.Integer(), nullable=False),
    sa.Column('video_address', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('registerd', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['robot_id'], ['robot.robot_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('chat_log',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('robot_log_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['robot_log_id'], ['robot_log.log_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_log')
    op.drop_table('robot_log')
    op.drop_table('cctv_log')
    op.drop_table('user')
    op.drop_table('robot')
    op.drop_table('cctv')
    op.drop_table('station')
    # ### end Alembic commands ###
